AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Telegram Bot Lambda function (ZIP deployment)

Parameters:
  TelegramBotToken:
    Type: String
    Description: "The Telegram Bot Token (obtain from BotFather)"
    NoEcho: true
  AuthorizedUserIds:
    Type: String
    Description: "Comma-separated list of authorized Telegram User IDs"
  TargetChannelId:
    Type: String
    Description: "The ID of the target Telegram channel for reposts (e.g., -100xxxxxxxxxx or @channelusername)"
  TelegramWebhookSecretToken:
    Type: String
    Description: "A secret token used to verify webhook requests from Telegram. Should be a long random string."
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Architectures:
        - x86_64
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          AUTHORIZED_USER_IDS: !Ref AuthorizedUserIds
          TARGET_CHANNEL_ID: !Ref TargetChannelId
          TELEGRAM_WEBHOOK_SECRET_TOKEN: !Ref TelegramWebhookSecretToken
      Events:
        TelegramWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId: !Ref ServerlessRestApi
    # Metadata section removed for Zip deployment

Outputs:
  TelegramBotApiEndpoint:
    Description: "API Gateway endpoint URL for your Telegram Bot Webhook. Register this URL with Telegram and provide the Webhook Secret Token."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook" # THIS IS THE INTENDED CORRECT SYNTAX
  TelegramBotFunctionArn:
    Description: "Telegram Bot Lambda Function ARN"
    Value: !GetAtt TelegramBotFunction.Arn
  TelegramBotFunctionIamRoleArn:
    Description: "Implicit IAM Role created for Telegram Bot function"
    Value: !GetAtt TelegramBotFunctionRole.Arn
