AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Telegram Bot Lambda function (ZIP deployment)

Parameters:
  TelegramBotToken:
    Type: String
    Description: "The Telegram Bot Token (obtain from BotFather)"
    NoEcho: true
  AuthorizedUserIds:
    Type: String
    Description: "Comma-separated list of authorized Telegram User IDs"
  TargetChannelId:
    Type: String
    Description: "The ID of the target Telegram channel for reposts (e.g., -100xxxxxxxxxx or @channelusername)"
  TelegramWebhookSecretToken:
    Type: String
    Description: "A secret token used to verify webhook requests from Telegram. Should be a long random string."
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    MemorySize: 256 # Can be adjusted based on needs

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip # MODIFIED
      Handler: lambda_function.lambda_handler # MODIFIED (points to src/lambda_function.py, function lambda_handler)
      Runtime: python3.9 # MODIFIED
      CodeUri: src/ # MODIFIED (points to the directory containing the handler)
      Architectures: # Can often be omitted for Zip, but good to specify if known
        - x86_64 # or arm64 if preferred and supported by runtime
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          AUTHORIZED_USER_IDS: !Ref AuthorizedUserIds
          TARGET_CHANNEL_ID: !Ref TargetChannelId
          TELEGRAM_WEBHOOK_SECRET_TOKEN: !Ref TelegramWebhookSecretToken
      Events:
        TelegramWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId: !Serverless::Api # Implicitly creates an API Gateway
    # REMOVED Metadata section that contained DockerTag, DockerContext, Dockerfile

Outputs:
  TelegramBotApiEndpoint:
    Description: "API Gateway endpoint URL for your Telegram Bot Webhook. Register this URL with Telegram and provide the Webhook Secret Token."
    Value: !Sub "https://\${ServerlessRestApi}.execute-api.\${AWS::Region}.amazonaws.com/\${Serverless::Stage}/webhook"
  TelegramBotFunctionArn:
    Description: "Telegram Bot Lambda Function ARN"
    Value: !GetAtt TelegramBotFunction.Arn
  TelegramBotFunctionIamRoleArn:
    Description: "Implicit IAM Role created for Telegram Bot function"
    Value: !GetAtt TelegramBotFunctionRole.Arn
