name: Deploy Telegram Bot to AWS Lambda (ZIP)

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

permissions:
  id-token: write # Required for OIDC AWS authentication
  contents: read  # Required to check out the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_FOR_GITHUB_ACTIONS }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --s3-bucket ${{ vars.SAM_CLI_S3_BUCKET }} \
            --s3-prefix telegram-bot-deployments \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              ParameterKey=TelegramBotToken,ParameterValue='${{ secrets.TELEGRAM_BOT_TOKEN }}' \
              ParameterKey=AuthorizedUserIds,ParameterValue='${{ vars.AUTHORIZED_USER_IDS }}' \
              ParameterKey=TargetChannelId,ParameterValue='${{ vars.TARGET_CHANNEL_ID }}' \
              ParameterKey=TelegramWebhookSecretToken,ParameterValue='${{ secrets.TELEGRAM_WEBHOOK_SECRET_TOKEN }}' \
              ParameterKey=AnnouncementTableName,ParameterValue='${{ vars.ANNOUNCEMENT_TABLE_NAME }}' \
            --stack-name telegram-bot-stack
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
